version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g @angular/cli

  pre_build:
    commands:
      - npm install
      - ng build --prod

  build:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y nginx
      - sudo rm -rf /var/www/html/*
      - sudo cp -R dist/* /var/www/html/
      - sudo rm /etc/nginx/sites-available/default
      - sudo rm /etc/nginx/sites-enabled/default
      - sudo tee /etc/nginx/sites-available/angular-app > /dev/null <<EOF
        server {
          listen 80;
          root /var/www/html;
          index index.html;
          location / {
            try_files $uri $uri/ /index.html;
          }
        }
        EOF
      - sudo ln -s /etc/nginx/sites-available/angular-app /etc/nginx/sites-enabled/
      - sudo systemctl restart nginx

artifacts:
  files:
    - '**/*'
  base-directory: ./dist/
